---
# NOTE: this is simply here to allow usage basic usage of tools like open-lens
# as they depend on the ability to list namespaces for all basic functions
- name: create a simple cluster role that allows you to list namespaces
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name:  list-namespaces
      rules:
      - apiGroups:
        - ""
        resources:
        - namespaces
        verbs:
        - list
