---
- name: create a role allowing access to the web namespace for our webdevs
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: webdevs-readonly
        namespace: web
      rules:
      - apiGroups:
        - ""
        resources:
        - pods
        - services
        verbs:
        - get
        - list
        - watch

- name: create the ns web binding
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name:  demo-webdevs-databases-binding
        namespace: web
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: webdevs-readonly
      subjects:
        - kind: Group
          name: webdevs
          apiGroup: rbac.authorization.k8s.io

- name: create the cluster role binding
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name:  demo-webdevs-list-namespaces
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: list-namespaces
      subjects:
        - kind: Group
          name: webdevs
          apiGroup: rbac.authorization.k8s.io
